source 'https://rubygems.org'
ruby '2.2.3'
gem 'rails'
gem 'responders'
gem 'draper'
gem 'arel'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks', github: 'rails/turbolinks'
gem 'rails_12factor', group: :production
gem 'puma'
gem 'jbuilder', '~> 2.0'
gem 'socky-server'
gem 'socky-client'
gem 'bootstrap-sass'
gem 'devise'
gem 'high_voltage'
gem 'pundit'
gem 'figaro'
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'spring'
  gem 'stackprof'
  gem 'rack-mini-profiler'
  gem 'flamegraph'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
