# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 8edf1e213ea68e12c912c07da10c3f8af32b0f70831c6d64ef86855ad0a7a423f1051bc71b1acab7f6088c98e59c298f2e70e0f70bd0af8a5f2d183596dbe707

test:
  domain_name: example.com
  secret_key_base: 8edf1e213ea68e12c912c07da10c3f8af32b0f70831c6d64ef86855ad0a7a423f1051bc71b1acab7f6088c98e59c298f2e70e0f70bd0af8a5f2d183596dbe707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
